server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service:80 # config-service를 Kubernetes에서 사용할 수 있는 이름으로 변경
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://polar-postgres:80/polardb_catalog # PostgreSQL 서비스 이름 사용
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://adb036ff5c06344c0aec6be4b15350c8-386055155.ap-southeast-2.elb.amazonaws.com/realms/PolarBookshop
#          issuer-uri: http://polar-keycloak:80/realms/PolarBookshop # Keycloak 서비스 이름 사용
  # Zipkin 설정 추가
#  sleuth:
#    sampler:
#      probability: 1.0 # 모든 요청을 샘플링 (프로덕션 환경에서는 이 값을 낮출 수 있습니다)
#  zipkin:
#    base-url: http://zipkin-service:80 # Zipkin 서버의 URL을 설정합니다
#    sender:
#      type: web # HTTP를 통해 Zipkin에 데이터를 전송합니다

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!
